### PR TITLE
Resolve #78 to restore 'Up-To-Date Check Verbose' Tweak

### LINKED ISSUE #78: Port to Community Toolkit - Regression
Not sure where to raise this one, but the issue is really now in the Community Toolkit.  In that, the `BaseOptionModel<T>` class blindly assumes the underlying type is a string. The Visual Studio Extensions window reports the following in my system (after a small tweak to the exception logging to accept a formatted string):
```
BaseOptionModel<Tweakster.Options>.LoadAsync Scope:UserSettings CollectionName:Tweakster.Options Name:U2DCheckVerbosity PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetString(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.BaseOptionModel`1.<LoadAsync>d__11.MoveNext()
BaseOptionModel<Tweakster.Options>.LoadAsync Scope:UserSettings CollectionName:Tweakster.Options Name:ShowBuildOrder PropertyType:System.Boolean Value:[NULL]
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellSettingsStore.GetString(String collectionPath, String propertyName)
   at Community.VisualStudio.Toolkit.BaseOptionModel`1.<LoadAsync>d__11.MoveNext()
```
My earlier PR added the attributes `OverrideCollectionNameAttribute` and `OverrideDataTypeAttribute` and these were checked for and honored by `BaseOptionModel`. While the attributes remain in Tweakster, the functionality of them is, of course, missing because these do not exist in the Community Toolkit.  

The combination of these attributes and functionality honoring them in `BaseOptionModel` enables an extension author to tweak a setting elsewhere in the hive. Do you think it would be acceptable to create a PR moving these attributes and implementation to the Community Toolkit, followed by a fix for this here once that PR is accepted?

### PR DESCRIPTION
**Pull request by StevenBonePgh**
Update to newest Community.VisualStudio.Toolkit and use attributes defined there.

### CODE REVIEW

File: src/Tweaks/Build/Options.cs [hunk 1]
```diff
@@ -17,5 +17,22 @@ internal partial class Options : BaseOptionModel<Options>
...
+        ///             <see cref="OverrideCollectionNameAttribute"/> and <see cref="OverrideDataTypeAttribute"/>
+        ///             have been applied so the value is loaded/saved in the appropriate place and is of
+        ///             the appropriate type. <a href="https://github.com/madskristensen/Tweakster/issues/60">
+        ///             Issue documentation</a> </remarks>
+        [Category(_build)]
+        [DisplayName("Up-To-Date Check Verbose")]
+        [Description("If Enabled, the Build Output Windows will output the reason why a project is being built.")]
+        [DefaultValue(false)]
+        [OverrideCollectionName("General")]
+        [OverrideDataType(SettingDataType.Bool)]
```
Comment (madskristensen) [inline src/Tweaks/Build/Options.cs]: What does it solve to add all this to the options?

Comment (StevenBonePgh) [reply src/Tweaks/Build/Options.cs]: I'm not sure I understand the question. This Tweak is used to change a Visual Studio option hidden in the private registry hive that has no GUI setting [see comment here](https://developercommunity.visualstudio.com/t/full-build-every-time-with-155/161997#T-N162336). It made sense to add it to the Build tweaks since it fits in there nicely with the other options.

Comment (madskristensen) [reply src/Tweaks/Build/Options.cs]: Ahh, I missed that part. Thanks for clarifying
